syntax = "proto3";

option java_multiple_files = true;
option java_package = "es.um.sisdist.backend.grpc";

package es.um.sisdist.backend.grpc;

service GrpcService
{
	rpc Ping(PingRequest) returns (PingResponse);
    rpc PreguntarLlama(PromptRequest) returns (TicketResponse);
	rpc ConsultaTicket(TicketRequest) returns (PromptResponse);
}

message PingRequest
{
	int32 v = 1;
}

message PingResponse
{
	int32 v = 1;
}

message PromptRequest
{
	//id del usuario
	string id_user = 1;
	string prompt_request = 2; 
}

message TicketResponse
{
	string status = 1;
	string ticket_response = 2;
}

message TicketRequest
{
	string id_user = 1;
	string ticket_request = 2;
}

message PromptResponse
{
	string status = 1;
	string response = 2;
}
